# Configuração Netlify para TranspJardim
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--production=false"

# Configuração de redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co;"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuração de formulários (caso necessário no futuro)
[forms]
  settings = true

# Configuração de Edge Functions (caso migre Supabase Functions)
[edge_functions]
  directory = "netlify/edge-functions"